version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_INIT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_INIT_PASSWORD}
      - MONGO_INITDB_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_AUTH_SOURCE}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DATABASE_INIT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DATABASE_INIT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
  reminder-app-backend:
    image: reminder-app-backend:1.0
    ports:
      - 8000:8000
    depends_on:
      - mongo-express
volumes:
  mongo-data:
    driver: local